Repository javascript-tutorial/es.javascript.info, pull requests merged in 2020-06, with the labels that each got.

#223 Sincronización 99-js-misc
  1-js/99-js-misc/01-proxy/01-error-nonexisting/solution.md
  1-js/99-js-misc/01-proxy/01-error-nonexisting/task.md
  1-js/99-js-misc/01-proxy/02-array-negative/solution.md
  1-js/99-js-misc/01-proxy/02-array-negative/task.md
  1-js/99-js-misc/01-proxy/03-observable/solution.md
  1-js/99-js-misc/01-proxy/03-observable/task.md
  1-js/99-js-misc/01-proxy/article.md
  1-js/99-js-misc/01-proxy/proxy-inherit-admin.svg
  1-js/99-js-misc/01-proxy/proxy-inherit.svg
  1-js/99-js-misc/01-proxy/proxy.svg
  1-js/99-js-misc/02-eval/1-eval-calculator/solution.md
  1-js/99-js-misc/02-eval/1-eval-calculator/task.md
  1-js/99-js-misc/02-eval/article.md
  1-js/99-js-misc/03-currying-partials/article.md
  1-js/99-js-misc/04-reference-type/2-check-syntax/solution.md
  1-js/99-js-misc/04-reference-type/2-check-syntax/task.md
  1-js/99-js-misc/04-reference-type/3-why-this/solution.md
  1-js/99-js-misc/04-reference-type/3-why-this/task.md
  1-js/99-js-misc/04-reference-type/article.md
  1-js/99-js-misc/05-bigint/article.md
  1-js/99-js-misc/index.md
Labels: needs +1

#222 Sincronización 13-modules
  1-js/13-modules/02-import-export/article.md
  1-js/13-modules/03-modules-dynamic-imports/article.md
Labels: needs +1

#221 Sincronización 12-generators-iterators
  1-js/12-generators-iterators/1-generators/01-pseudo-random-generator/solution.md
  1-js/12-generators-iterators/1-generators/01-pseudo-random-generator/task.md
  1-js/12-generators-iterators/1-generators/article.md
  1-js/12-generators-iterators/1-generators/genYield2-2.svg
  1-js/12-generators-iterators/1-generators/genYield2.svg
  1-js/12-generators-iterators/1-generators/generateSequence-1.svg
  1-js/12-generators-iterators/1-generators/generateSequence-2.svg
  1-js/12-generators-iterators/1-generators/generateSequence-3.svg
  1-js/12-generators-iterators/1-generators/generateSequence-4.svg
  1-js/12-generators-iterators/2-async-iterators-generators/article.md
  1-js/12-generators-iterators/2-async-iterators-generators/head.html
Labels: needs +1

#220 Sincronización 11-async
  1-js/11-async/01-callbacks/article.md
  1-js/11-async/01-callbacks/callback-hell.svg
  1-js/11-async/02-promise-basics/article.md
  1-js/11-async/02-promise-basics/promise-reject-1.svg
  1-js/11-async/02-promise-basics/promise-resolve-1.svg
  1-js/11-async/02-promise-basics/promise-resolve-reject.svg
  1-js/11-async/03-promise-chaining/01-then-vs-catch/solution.md
  1-js/11-async/03-promise-chaining/article.md
  1-js/11-async/03-promise-chaining/head.html
  1-js/11-async/03-promise-chaining/promise-handler-variants.svg
  1-js/11-async/03-promise-chaining/promise-then-chain.svg
  1-js/11-async/03-promise-chaining/promise-then-many.svg
  1-js/11-async/04-promise-error-handling/article.md
  1-js/11-async/04-promise-error-handling/head.html
  1-js/11-async/04-promise-error-handling/promise-handler-variants.svg
  1-js/11-async/04-promise-error-handling/promise-then-chain.svg
  1-js/11-async/04-promise-error-handling/promise-then-many.svg
  1-js/11-async/05-promise-api/01-promise-errors-as-results/solution.md
  1-js/11-async/05-promise-api/01-promise-errors-as-results/solution.view/index.html
  1-js/11-async/05-promise-api/01-promise-errors-as-results/source.view/index.html
  1-js/11-async/05-promise-api/01-promise-errors-as-results/task.md
  1-js/11-async/05-promise-api/02-promise-errors-as-results-2/solution.md
  1-js/11-async/05-promise-api/02-promise-errors-as-results-2/solution.view/index.html
  1-js/11-async/05-promise-api/02-promise-errors-as-results-2/source.view/index.html
  1-js/11-async/05-promise-api/02-promise-errors-as-results-2/task.md
  1-js/11-async/05-promise-api/article.md
  1-js/11-async/06-promisify/article.md
  1-js/11-async/07-microtask-queue/article.md
  1-js/11-async/07-microtask-queue/eventLoop.svg
  1-js/11-async/07-microtask-queue/promiseQueue.svg
  1-js/11-async/08-async-await/01-rewrite-async/solution.md
  1-js/11-async/08-async-await/01-rewrite-async/task.md
  1-js/11-async/08-async-await/02-rewrite-async-2/task.md
  1-js/11-async/08-async-await/article.md
Labels: needs +1

#219 Sincronización 10-error-handling
  1-js/10-error-handling/1-try-catch/1-finally-or-code-after/solution.md
  1-js/10-error-handling/1-try-catch/1-finally-or-code-after/task.md
  1-js/10-error-handling/1-try-catch/article.md
  1-js/10-error-handling/1-try-catch/try-catch-flow.svg
  1-js/10-error-handling/2-custom-errors/1-format-error/solution.md
  1-js/10-error-handling/2-custom-errors/article.md
Labels: needs +1

#218 Sincronización 09-classes
  1-js/09-classes/01-class/article.md
  1-js/09-classes/01-class/class-user.svg
  1-js/09-classes/02-class-inheritance/2-clock-class-extended/solution.view/extended-clock.js
  1-js/09-classes/02-class-inheritance/3-class-extend-object/rabbit-extends-object.svg
  1-js/09-classes/02-class-inheritance/3-class-extend-object/solution.md
  1-js/09-classes/02-class-inheritance/3-class-extend-object/task.md
  1-js/09-classes/02-class-inheritance/animal-rabbit-extends.svg
  1-js/09-classes/02-class-inheritance/article.md
  1-js/09-classes/02-class-inheritance/class-inheritance-array-object.svg
  1-js/09-classes/02-class-inheritance/class-inheritance-rabbit-animal-2.svg
  1-js/09-classes/02-class-inheritance/class-inheritance-rabbit-animal.svg
  1-js/09-classes/02-class-inheritance/rabbit-animal-independent-animal.svg
  1-js/09-classes/02-class-inheritance/rabbit-animal-independent-rabbit.svg
  1-js/09-classes/02-class-inheritance/super-homeobject-wrong.svg
  1-js/09-classes/02-class-inheritance/this-super-loop.svg
  1-js/09-classes/03-static-properties-methods/animal-rabbit-static.svg
  1-js/09-classes/03-static-properties-methods/article.md
  1-js/09-classes/04-private-protected-properties-methods/article.md
  1-js/09-classes/05-extend-natives/article.md
  1-js/09-classes/05-extend-natives/object-date-inheritance.svg
  1-js/09-classes/06-instanceof/1-strange-instanceof/task.md
  1-js/09-classes/06-instanceof/article.md
  1-js/09-classes/06-instanceof/instanceof.svg
  1-js/09-classes/07-mixins/article.md
  1-js/09-classes/07-mixins/head.html
  1-js/09-classes/07-mixins/mixin-inheritance.svg
Labels: needs +1

#217 Sincronización 07-object-properties
  1-js/07-object-properties/01-property-descriptors/article.md
  1-js/07-object-properties/02-property-accessors/article.md
Labels: needs +1

#216 Sincronización 08-prototypes
  1-js/08-prototypes/01-prototype-inheritance/2-search-algorithm/task.md
  1-js/08-prototypes/01-prototype-inheritance/3-proto-and-this/solution.md
  1-js/08-prototypes/01-prototype-inheritance/3-proto-and-this/task.md
  1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/solution.md
  1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/task.md
  1-js/08-prototypes/01-prototype-inheritance/article.md
  1-js/08-prototypes/01-prototype-inheritance/object-prototype-empty.svg
  1-js/08-prototypes/01-prototype-inheritance/proto-animal-rabbit-chain.svg
  1-js/08-prototypes/01-prototype-inheritance/proto-animal-rabbit-walk-2.svg
  1-js/08-prototypes/01-prototype-inheritance/proto-animal-rabbit-walk-3.svg
  1-js/08-prototypes/01-prototype-inheritance/proto-animal-rabbit-walk.svg
  1-js/08-prototypes/01-prototype-inheritance/proto-animal-rabbit.svg
  1-js/08-prototypes/01-prototype-inheritance/proto-user-admin.svg
  1-js/08-prototypes/01-prototype-inheritance/rabbit-animal-object.svg
  1-js/08-prototypes/02-function-prototype/1-changing-prototype/solution.md
  1-js/08-prototypes/02-function-prototype/1-changing-prototype/task.md
  1-js/08-prototypes/02-function-prototype/4-new-object-same-constructor/solution.md
  1-js/08-prototypes/02-function-prototype/article.md
  1-js/08-prototypes/02-function-prototype/function-prototype-constructor.svg
  1-js/08-prototypes/02-function-prototype/native-prototypes-array-tostring.svg
  1-js/08-prototypes/02-function-prototype/native-prototypes-classes.svg
  1-js/08-prototypes/02-function-prototype/object-prototype-1.svg
  1-js/08-prototypes/02-function-prototype/object-prototype.svg
  1-js/08-prototypes/02-function-prototype/proto-constructor-animal-rabbit.svg
  1-js/08-prototypes/02-function-prototype/rabbit-animal-object.svg
  1-js/08-prototypes/02-function-prototype/rabbit-prototype-constructor.svg
  1-js/08-prototypes/03-native-prototypes/2-defer-to-prototype-extended/solution.md
  1-js/08-prototypes/03-native-prototypes/article.md
  1-js/08-prototypes/03-native-prototypes/function-prototype-constructor.svg
  1-js/08-prototypes/03-native-prototypes/native-prototypes-array-tostring.svg
  1-js/08-prototypes/03-native-prototypes/native-prototypes-classes.svg
  1-js/08-prototypes/03-native-prototypes/object-prototype-1.svg
  1-js/08-prototypes/03-native-prototypes/object-prototype-null.svg
  1-js/08-prototypes/03-native-prototypes/object-prototype.svg
  1-js/08-prototypes/03-native-prototypes/proto-constructor-animal-rabbit.svg
  1-js/08-prototypes/03-native-prototypes/rabbit-prototype-constructor.svg
  1-js/08-prototypes/04-prototype-methods/article.md
  1-js/08-prototypes/04-prototype-methods/object-prototype-2.svg
  1-js/08-prototypes/04-prototype-methods/object-prototype-null.svg
  1-js/08-prototypes/05-getting-all-properties/article.md
  1-js/08-prototypes/05-getting-all-properties/rabbit-animal-object.svg
Labels: needs +1

#213 Sincronización 04-object-basic
  1-js/04-object-basics/01-object/4-const-object/solution.md
  1-js/04-object-basics/01-object/4-const-object/task.md
  1-js/04-object-basics/01-object/article.md
  1-js/04-object-basics/01-object/object-user-delete.svg
  1-js/04-object-basics/01-object/object-user-empty.svg
  1-js/04-object-basics/01-object/object-user-isadmin.svg
  1-js/04-object-basics/01-object/object-user-props.svg
  1-js/04-object-basics/01-object/object-user.svg
  1-js/04-object-basics/01-object/object.svg
  1-js/04-object-basics/01-object/variable-contains-reference.svg
  1-js/04-object-basics/01-object/variable-copy-reference.svg
  1-js/04-object-basics/01-object/variable-copy-value.svg
  1-js/04-object-basics/02-garbage-collection/family-delete-refs.svg
  1-js/04-object-basics/02-garbage-collection/family-no-family.svg
  1-js/04-object-basics/02-garbage-collection/family-no-father-2.svg
  1-js/04-object-basics/02-garbage-collection/family-no-father.svg
  1-js/04-object-basics/02-garbage-collection/family.svg
  1-js/04-object-basics/02-garbage-collection/garbage-collection-1.svg
  1-js/04-object-basics/02-garbage-collection/garbage-collection-2.svg
  1-js/04-object-basics/02-garbage-collection/garbage-collection-3.svg
  1-js/04-object-basics/02-garbage-collection/garbage-collection-4.svg
  1-js/04-object-basics/02-garbage-collection/garbage-collection-5.svg
  1-js/04-object-basics/02-garbage-collection/memory-user-john-admin.svg
  1-js/04-object-basics/02-garbage-collection/memory-user-john-lost.svg
  1-js/04-object-basics/02-garbage-collection/memory-user-john.svg
  1-js/04-object-basics/02-object-copy/article.md
  1-js/04-object-basics/02-object-copy/variable-contains-reference.svg
  1-js/04-object-basics/02-object-copy/variable-copy-reference.svg
  1-js/04-object-basics/02-object-copy/variable-copy-value.svg
  1-js/04-object-basics/03-garbage-collection/article.md
  1-js/04-object-basics/03-garbage-collection/family-delete-refs.svg
  1-js/04-object-basics/03-garbage-collection/family-no-family.svg
  1-js/04-object-basics/03-garbage-collection/family-no-father-2.svg
  1-js/04-object-basics/03-garbage-collection/family-no-father.svg
  1-js/04-object-basics/03-garbage-collection/family.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-1.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-2.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-3.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-4.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-5.svg
  1-js/04-object-basics/03-garbage-collection/memory-user-john-admin.svg
  1-js/04-object-basics/03-garbage-collection/memory-user-john-lost.svg
  1-js/04-object-basics/03-garbage-collection/memory-user-john.svg
  1-js/04-object-basics/04-object-methods/2-check-syntax/solution.md
  1-js/04-object-basics/04-object-methods/2-check-syntax/task.md
  1-js/04-object-basics/04-object-methods/3-why-this/solution.md
  1-js/04-object-basics/04-object-methods/3-why-this/task.md
  1-js/04-object-basics/04-object-methods/4-object-property-this/solution.md
  1-js/04-object-basics/04-object-methods/article.md
  1-js/04-object-basics/05-object-toprimitive/article.md
  1-js/04-object-basics/06-constructor-new/3-accumulator/task.md
  1-js/04-object-basics/06-constructor-new/article.md
  1-js/04-object-basics/07-optional-chaining/article.md
  1-js/04-object-basics/08-symbol/article.md
  1-js/04-object-basics/09-object-toprimitive/article.md
Labels: needs +1

#212 Sincronización-03-code-quality
  1-js/03-code-quality/01-debugging-chrome/article.md
  1-js/03-code-quality/01-debugging-chrome/chrome-open-sources.svg
  1-js/03-code-quality/01-debugging-chrome/chrome-sources-breakpoint.svg
  1-js/03-code-quality/01-debugging-chrome/chrome-sources-console.svg
  1-js/03-code-quality/01-debugging-chrome/chrome-sources-debugger-pause.svg
  1-js/03-code-quality/01-debugging-chrome/chrome-sources-debugger-trace-1.svg
  1-js/03-code-quality/01-debugging-chrome/chrome-tabs.svg
  1-js/03-code-quality/01-debugging-chrome/head.html
  1-js/03-code-quality/01-debugging-chrome/largeIcons.svg
  1-js/03-code-quality/01-debugging-chrome/toolbarButtonGlyphs.svg
  1-js/03-code-quality/02-coding-style/article.md
  1-js/03-code-quality/02-coding-style/code-style.svg
  1-js/03-code-quality/02-coding-style/figure-bracket-style.png
  1-js/03-code-quality/02-coding-style/figure-bracket-style@2x.png
  1-js/03-code-quality/03-comments/article.md
  1-js/03-code-quality/04-ninja-code/article.md
  1-js/03-code-quality/05-testing-mocha/3-pow-test-wrong/solution.md
  1-js/03-code-quality/05-testing-mocha/article.md
  1-js/03-code-quality/05-testing-mocha/pow-2.view/test.js
  1-js/03-code-quality/06-polyfills/article.md
Labels: needs +1

#211 Sincronización-02-first-steps
  1-js/02-first-steps/01-hello-world/1-hello-alert/index.html
  1-js/02-first-steps/06-alert-prompt-confirm/1-simple-page/solution.md
  1-js/02-first-steps/06-alert-prompt-confirm/1-simple-page/task.md
  1-js/02-first-steps/06-alert-prompt-confirm/article.md
  1-js/02-first-steps/06-type-conversions/1-primitive-conversions-questions/solution.md
  1-js/02-first-steps/07-type-conversions/article.md
  1-js/02-first-steps/08-operators/1-increment-order/solution.md
  1-js/02-first-steps/08-operators/1-increment-order/task.md
  1-js/02-first-steps/08-operators/2-assignment-result/solution.md
  1-js/02-first-steps/08-operators/2-assignment-result/task.md
  1-js/02-first-steps/08-operators/3-primitive-conversions-questions/solution.md
  1-js/02-first-steps/08-operators/3-primitive-conversions-questions/task.md
  1-js/02-first-steps/08-operators/4-fix-prompt/solution.md
  1-js/02-first-steps/08-operators/4-fix-prompt/task.md
  1-js/02-first-steps/08-operators/article.md
  1-js/02-first-steps/09-comparison/1-comparison-questions/solution.md
  1-js/02-first-steps/09-comparison/1-comparison-questions/task.md
  1-js/02-first-steps/09-comparison/article.md
  1-js/02-first-steps/17-arrow-functions-basics/1-rewrite-arrow/solution.md
  1-js/02-first-steps/17-arrow-functions-basics/1-rewrite-arrow/task.md
  1-js/02-first-steps/17-arrow-functions-basics/article.md
Labels: needs +1

#226 1 11 async 1 article + task - No tocar ni revisar ni nada
  11-async/01-callbacks/01-animate-circle-callback/solution.md
  11-async/01-callbacks/article.md
Labels: review needed

#206 Function binding
  1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/solution.md
  1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/task.md
  1-js/06-advanced-functions/10-bind/3-second-bind/solution.md
  1-js/06-advanced-functions/10-bind/3-second-bind/task.md
  1-js/06-advanced-functions/10-bind/4-function-property-after-bind/solution.md
  1-js/06-advanced-functions/10-bind/4-function-property-after-bind/task.md
  1-js/06-advanced-functions/10-bind/5-question-use-bind/solution.md
  1-js/06-advanced-functions/10-bind/5-question-use-bind/task.md
  1-js/06-advanced-functions/10-bind/6-ask-partial/solution.md
  1-js/06-advanced-functions/10-bind/6-ask-partial/task.md
  1-js/06-advanced-functions/10-bind/article.md
Labels: needs +1

#204 Arrow functions revisited
  1-js/06-advanced-functions/12-arrow-functions/article.md
Labels: needs +1

#195 Prototype methods, objects without __proto__
  1-js/08-prototypes/04-prototype-methods/2-dictionary-tostring/solution.md
  1-js/08-prototypes/04-prototype-methods/2-dictionary-tostring/task.md
  1-js/08-prototypes/04-prototype-methods/3-compare-calls/solution.md
  1-js/08-prototypes/04-prototype-methods/3-compare-calls/task.md
  1-js/08-prototypes/04-prototype-methods/article.md
  1-js/08-prototypes/index.md
Labels: needs +1

#45 Promisification
  1-js/11-async/06-promisify/article.md
Labels: changes requested

#70 Tarea
  1-js/02-first-steps/04-variables/3-uppercast-constant/task.md
Labels: changes requested

#200 Numbers
  1-js/05-data-types/02-number/1-sum-interface/solution.md
  1-js/05-data-types/02-number/1-sum-interface/task.md
  1-js/05-data-types/02-number/2-why-rounded-down/solution.md
  1-js/05-data-types/02-number/2-why-rounded-down/task.md
  1-js/05-data-types/02-number/3-repeat-until-number/solution.md
  1-js/05-data-types/02-number/3-repeat-until-number/task.md
  1-js/05-data-types/02-number/4-endless-loop-error/solution.md
  1-js/05-data-types/02-number/4-endless-loop-error/task.md
  1-js/05-data-types/02-number/8-random-min-max/solution.md
  1-js/05-data-types/02-number/8-random-min-max/task.md
  1-js/05-data-types/02-number/9-random-int-min-max/solution.md
  1-js/05-data-types/02-number/9-random-int-min-max/task.md
  1-js/05-data-types/02-number/article.md
Labels: needs +1

#229 JavaScript specials
  1-js/02-first-steps/18-javascript-specials/article.md
Labels: needs +1

#208 Export and Import
  1-js/13-modules/02-import-export/article.md
Labels: needs +1

#143 Spelling corrections
  1-js/01-getting-started/1-intro/article.md
Labels: needs +1

#109 Ninja code
  1-js/03-code-quality/04-ninja-code/article.md
Labels: needs +1

#82 LocalStorage, sessionStorage
  6-data-storage/02-localstorage/article.md
Labels: needs +1

#108 Translated Comments, Polyfills and index
  1-js/03-code-quality/03-comments/article.md
  1-js/03-code-quality/06-polyfills/article.md
  1-js/03-code-quality/index.md
  1-js/index.md
Labels: changes requested

#101 Debugging in Chrome
  1-js/03-code-quality/01-debugging-chrome/article.md
  1-js/03-code-quality/01-debugging-chrome/chrome-open-sources.svg
  1-js/03-code-quality/01-debugging-chrome/chrome-sources-breakpoint.svg
  1-js/03-code-quality/01-debugging-chrome/chrome-sources-debugger-pause.svg
  1-js/03-code-quality/01-debugging-chrome/debugging.view/index.html
Labels: changes requested

#110 CSS Animations
  7-animation/2-css-animations/1-animate-logo-css/solution.md
  7-animation/2-css-animations/1-animate-logo-css/task.md
  7-animation/2-css-animations/2-animate-logo-bezier-css/solution.md
  7-animation/2-css-animations/2-animate-logo-bezier-css/task.md
  7-animation/2-css-animations/3-animate-circle/task.md
  7-animation/2-css-animations/article.md
  7-animation/2-css-animations/boat.view/index.html
  7-animation/2-css-animations/digits-negative-delay.view/index.html
  7-animation/2-css-animations/digits.view/index.html
  7-animation/2-css-animations/step-end.view/index.html
  7-animation/2-css-animations/step.view/index.html
Labels: changes requested

#93 Variables
  1-js/02-first-steps/04-variables/article.md
Labels: changes requested

#236 sync-16-function-expressions
  1-js/02-first-steps/16-function-expressions-arrows/1-rewrite-arrow/solution.md
  1-js/02-first-steps/16-function-expressions-arrows/1-rewrite-arrow/task.md
  1-js/02-first-steps/16-function-expressions/article.md
Labels: needs +1

#239 sync-ui-events
  2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/solution.md
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/move-ball-coords.svg
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
  2-ui/2-events/01-introduction-browser-events/05-sliding-menu/solution.md
  2-ui/2-events/01-introduction-browser-events/07-carousel/carousel1.svg
  2-ui/2-events/01-introduction-browser-events/07-carousel/carousel2.svg
  2-ui/2-events/01-introduction-browser-events/07-carousel/solution.md
  2-ui/2-events/01-introduction-browser-events/article.md
  2-ui/2-events/02-bubbling-and-capturing/article.md
  2-ui/2-events/02-bubbling-and-capturing/event-order-bubbling.svg
  2-ui/2-events/02-bubbling-and-capturing/eventflow.svg
  2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md
  2-ui/2-events/03-event-delegation/article.md
  2-ui/2-events/03-event-delegation/bagua-bubble.svg
  2-ui/2-events/04-default-browser-action/1-why-return-false-fails/solution.md
  2-ui/2-events/04-default-browser-action/1-why-return-false-fails/task.md
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/solution.view/index.html
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/source.view/index.html
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/task.md
  2-ui/2-events/04-default-browser-action/article.md
  2-ui/2-events/05-dispatch-events/article.md
Labels: needs +1

#241 sync-ui-forms-controls
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/task.md
  2-ui/4-forms-controls/1-form-elements/article.md
  2-ui/4-forms-controls/1-form-elements/form-navigation.svg
  2-ui/4-forms-controls/2-focus-blur/3-editable-div/solution.view/my.css
  2-ui/4-forms-controls/2-focus-blur/3-editable-div/source.view/my.css
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/solution.view/my.css
  2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/solution.md
  2-ui/4-forms-controls/2-focus-blur/article.md
  2-ui/4-forms-controls/3-events-change-input/article.md
  2-ui/4-forms-controls/4-forms-submit/article.md
Labels: needs +1

#242 sync-ui-loading-99misc
  2-ui/5-loading/01-onload-ondomcontentloaded/article.md
  2-ui/5-loading/02-script-async-defer/article.md
  2-ui/5-loading/02-script-async-defer/window-onbeforeunload.view/index.html
  2-ui/5-loading/03-onload-onerror/1-load-img-callback/solution.view/index.html
  2-ui/5-loading/03-onload-onerror/article.md
  2-ui/99-ui-misc/01-mutation-observer/article.md
  2-ui/99-ui-misc/02-selection-range/article.md
  2-ui/99-ui-misc/02-selection-range/range-example-p-0-1.svg
  2-ui/99-ui-misc/02-selection-range/range-example-p-1-3.svg
  2-ui/99-ui-misc/02-selection-range/range-example-p-2-b-3-range.svg
  2-ui/99-ui-misc/02-selection-range/range-example-p-2-b-3.svg
  2-ui/99-ui-misc/02-selection-range/selection-direction-backward.svg
  2-ui/99-ui-misc/02-selection-range/selection-direction-forward.svg
  2-ui/99-ui-misc/02-selection-range/selection-firefox.svg
  2-ui/99-ui-misc/03-event-loop/article.md
  2-ui/99-ui-misc/03-event-loop/eventLoop-full.svg
  2-ui/99-ui-misc/03-event-loop/eventLoop.svg
  2-ui/99-ui-misc/index.md
Labels: needs +1

#202 Scheduling: setTimeout and setInterval
  1-js/06-advanced-functions/08-settimeout-setinterval/1-output-numbers-100ms/solution.md
  1-js/06-advanced-functions/08-settimeout-setinterval/1-output-numbers-100ms/task.md
  1-js/06-advanced-functions/08-settimeout-setinterval/4-settimeout-result/solution.md
  1-js/06-advanced-functions/08-settimeout-setinterval/4-settimeout-result/task.md
  1-js/06-advanced-functions/08-settimeout-setinterval/article.md
Labels: needs +1

#189 Promises chaining
  1-js/11-async/03-promise-chaining/01-then-vs-catch/solution.md
  1-js/11-async/03-promise-chaining/01-then-vs-catch/task.md
  1-js/11-async/03-promise-chaining/article.md
  1-js/11-async/03-promise-chaining/getMessage.js
  1-js/11-async/03-promise-chaining/head.html
Labels: needs +1

#243 sync-3-frames-and-windows
  3-frames-and-windows/01-popup-windows/article.md
  3-frames-and-windows/03-cross-window-communication/article.md
  3-frames-and-windows/06-clickjacking/article.md
Labels: needs +1

#244 sync-4-binary
  4-binary/01-arraybuffer-binary-arrays/8bit-integer-256.svg
  4-binary/01-arraybuffer-binary-arrays/8bit-integer-257.svg
  4-binary/01-arraybuffer-binary-arrays/arraybuffer-view-buffersource.svg
  4-binary/01-arraybuffer-binary-arrays/arraybuffer-views.svg
  4-binary/01-arraybuffer-binary-arrays/article.md
  4-binary/02-text-decoder/article.md
  4-binary/03-blob/article.md
  4-binary/03-blob/blob.svg
  4-binary/04-file/article.md
  4-binary/index.md
Labels: needs +1

#246 sync-6-data-storage
  6-data-storage/01-cookie/article.md
  6-data-storage/01-cookie/cookie-third-party-2.svg
  6-data-storage/01-cookie/cookie-third-party-3.svg
  6-data-storage/01-cookie/cookie-third-party.svg
  6-data-storage/01-cookie/cookie-xsrf.svg
  6-data-storage/01-cookie/cookie.js
  6-data-storage/02-localstorage/1-form-autosave/task.md
  6-data-storage/03-indexeddb/article.md
  6-data-storage/03-indexeddb/indexeddb-cursor.svg
  6-data-storage/03-indexeddb/indexeddb-index.svg
  6-data-storage/03-indexeddb/indexeddb-structure.svg
Labels: needs +1

#248 sync-8-web-components
  8-web-components/1-webcomponents-intro/article.md
  8-web-components/1-webcomponents-intro/web-components-twitter.svg
  8-web-components/2-custom-elements/article.md
  8-web-components/3-shadow-dom/article.md
  8-web-components/4-template-element/article.md
  8-web-components/5-slots-composition/article.md
  8-web-components/5-slots-composition/shadow-dom-user-card.svg
  8-web-components/6-shadow-dom-style/article.md
  8-web-components/7-shadow-dom-events/article.md
Labels: needs +1

#237 Patterns and flags
  9-regular-expressions/01-regexp-introduction/article.md
  9-regular-expressions/index.md
Labels: needs +1

#232 Introduction: callbacks
  1-js/11-async/01-callbacks/01-animate-circle-callback/solution.view/index.html
  1-js/11-async/01-callbacks/01-animate-circle-callback/task.md
  1-js/11-async/01-callbacks/article.md
Labels: needs +1

#116 Rest parameters and spread operator
  1-js/06-advanced-functions/02-rest-parameters-spread/article.md
Labels: needs +1

#176 WeakMap and WeakSet
  1-js/05-data-types/weakmap-weakset/01-recipients-read/solution.md
  1-js/05-data-types/weakmap-weakset/01-recipients-read/task.md
  1-js/05-data-types/weakmap-weakset/02-recipients-when-read/solution.md
  1-js/05-data-types/weakmap-weakset/02-recipients-when-read/task.md
  1-js/05-data-types/weakmap-weakset/article.md
Labels: needs +1

#258 Coding style
  1-js/03-code-quality/02-coding-style/1-style-errors/solution.md
  1-js/03-code-quality/02-coding-style/1-style-errors/task.md
  1-js/03-code-quality/02-coding-style/article.md
Labels: review needed

#120 The "new Function" syntax
  1-js/06-advanced-functions/07-new-function/article.md
Labels: needs +1

#260 Garbage Collection
  1-js/04-object-basics/03-garbage-collection/article.md
  1-js/04-object-basics/03-garbage-collection/family-delete-refs.svg
  1-js/04-object-basics/03-garbage-collection/family-no-family.svg
  1-js/04-object-basics/03-garbage-collection/family-no-father-2.svg
  1-js/04-object-basics/03-garbage-collection/family-no-father.svg
  1-js/04-object-basics/03-garbage-collection/family.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-1.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-2.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-3.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-4.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-5.svg
  1-js/04-object-basics/03-garbage-collection/memory-user-john-admin.svg
  1-js/04-object-basics/03-garbage-collection/memory-user-john-lost.svg
  1-js/04-object-basics/03-garbage-collection/memory-user-john.svg
Labels: review needed

#126 Strings
  1-js/05-data-types/03-string/1-ucfirst/_js.view/solution.js
  1-js/05-data-types/03-string/1-ucfirst/solution.md
  1-js/05-data-types/03-string/1-ucfirst/task.md
  1-js/05-data-types/03-string/2-check-spam/solution.md
  1-js/05-data-types/03-string/2-check-spam/task.md
  1-js/05-data-types/03-string/3-truncate/solution.md
  1-js/05-data-types/03-string/3-truncate/task.md
  1-js/05-data-types/03-string/4-extract-currency/task.md
  1-js/05-data-types/03-string/article.md
Labels: needs +1

#231 Conditional operators: if, '?'
  1-js/02-first-steps/10-ifelse/1-if-zero-string/solution.md
  1-js/02-first-steps/10-ifelse/1-if-zero-string/task.md
  1-js/02-first-steps/10-ifelse/2-check-standard/ifelse_task2.svg
  1-js/02-first-steps/10-ifelse/2-check-standard/ifelse_task2/index.html
  1-js/02-first-steps/10-ifelse/2-check-standard/task.md
  1-js/02-first-steps/10-ifelse/3-sign/if_sign/index.html
  1-js/02-first-steps/10-ifelse/3-sign/solution.md
  1-js/02-first-steps/10-ifelse/3-sign/task.md
  1-js/02-first-steps/10-ifelse/5-rewrite-if-question/solution.md
  1-js/02-first-steps/10-ifelse/5-rewrite-if-question/task.md
  1-js/02-first-steps/10-ifelse/6-rewrite-if-else-question/solution.md
  1-js/02-first-steps/10-ifelse/6-rewrite-if-else-question/task.md
  1-js/02-first-steps/10-ifelse/article.md
Labels: needs +1

#152 Automated testing with Mocha
  1-js/03-code-quality/05-testing-mocha/3-pow-test-wrong/solution.md
  1-js/03-code-quality/05-testing-mocha/3-pow-test-wrong/task.md
  1-js/03-code-quality/05-testing-mocha/article.md
  1-js/03-code-quality/05-testing-mocha/beforeafter.view/index.html
  1-js/03-code-quality/05-testing-mocha/beforeafter.view/test.js
  1-js/03-code-quality/05-testing-mocha/index.html
  1-js/03-code-quality/05-testing-mocha/pow-1.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-1.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-2.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-2.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-3.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-3.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-4.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-4.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-full.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-full.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-min.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-min.view/test.js
  1-js/03-code-quality/05-testing-mocha/pow-nan.view/index.html
  1-js/03-code-quality/05-testing-mocha/pow-nan.view/test.js
Labels: needs +1

#155 Recursion and stack
  1-js/06-advanced-functions/01-recursion/article.md
Labels: needs +1

#267 Hello, world!
  1-js/02-first-steps/01-hello-world/1-hello-alert/index.html
  1-js/02-first-steps/01-hello-world/1-hello-alert/solution.md
  1-js/02-first-steps/01-hello-world/2-hello-alert-ext/alert.js
  1-js/02-first-steps/01-hello-world/2-hello-alert-ext/solution.md
  1-js/02-first-steps/01-hello-world/2-hello-alert-ext/task.md
  1-js/02-first-steps/01-hello-world/article.md
Labels: needs +1

#199 Methods of primitives
  1-js/05-data-types/01-primitives-methods/1-string-new-property/solution.md
  1-js/05-data-types/01-primitives-methods/1-string-new-property/task.md
  1-js/05-data-types/01-primitives-methods/article.md
Labels: review needed

#172 Static properties and methods
  1-js/09-classes/03-static-properties-methods/article.md
Labels: changes requested

#173 Private and protected properties and methods
  1-js/09-classes/04-private-protected-properties-methods/article.md
Labels: changes requested

#174 Extending built-in classes
  1-js/09-classes/05-extend-natives/article.md
Labels: needs +1

#175 Class checking: "instanceof"
  1-js/09-classes/06-instanceof/1-strange-instanceof/solution.md
  1-js/09-classes/06-instanceof/1-strange-instanceof/task.md
  1-js/09-classes/06-instanceof/article.md
Labels: needs +1

#178 Variable scope
  1-js/06-advanced-functions/03-closure/1-closure-latest-changes/solution.md
  1-js/06-advanced-functions/03-closure/1-closure-latest-changes/task.md
  1-js/06-advanced-functions/03-closure/10-make-army/solution.md
  1-js/06-advanced-functions/03-closure/10-make-army/task.md
  1-js/06-advanced-functions/03-closure/2-closure-variable-access/solution.md
  1-js/06-advanced-functions/03-closure/2-closure-variable-access/task.md
  1-js/06-advanced-functions/03-closure/3-counter-independent/solution.md
  1-js/06-advanced-functions/03-closure/3-counter-independent/task.md
  1-js/06-advanced-functions/03-closure/4-counter-object-independent/solution.md
  1-js/06-advanced-functions/03-closure/4-counter-object-independent/task.md
  1-js/06-advanced-functions/03-closure/5-function-in-if/solution.md
  1-js/06-advanced-functions/03-closure/5-function-in-if/task.md
  1-js/06-advanced-functions/03-closure/6-closure-sum/solution.md
  1-js/06-advanced-functions/03-closure/6-closure-sum/task.md
  1-js/06-advanced-functions/03-closure/7-let-scope/solution.md
  1-js/06-advanced-functions/03-closure/7-let-scope/task.md
  1-js/06-advanced-functions/03-closure/8-filter-through-function/solution.md
  1-js/06-advanced-functions/03-closure/8-filter-through-function/task.md
  1-js/06-advanced-functions/03-closure/9-sort-by-field/task.md
  1-js/06-advanced-functions/03-closure/article.md
Labels: needs +1

#276 Corrección sync
  1-js/09-classes/03-static-properties-methods/3-class-extend-object/rabbit-extends-object.svg
  1-js/09-classes/03-static-properties-methods/3-class-extend-object/solution.md
  1-js/09-classes/03-static-properties-methods/3-class-extend-object/task.md
Labels: review needed

#264 DOM tree
  2-ui/1-document/02-dom-nodes/article.md
Labels: needs +1

#179 Iterables
  1-js/05-data-types/06-iterable/article.md
Labels: needs +1

#181 Global object
  1-js/06-advanced-functions/05-global-object/article.md
Labels: needs +1

#182 Function object, NFE
  1-js/06-advanced-functions/06-function-object/2-counter-inc-dec/solution.md
  1-js/06-advanced-functions/06-function-object/2-counter-inc-dec/task.md
  1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/solution.md
  1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/task.md
  1-js/06-advanced-functions/06-function-object/article.md
Labels: needs +1

#194 Property getters and setters
  1-js/07-object-properties/02-property-accessors/article.md
Labels: needs +1

#285 Custom errors, extending Error
  1-js/10-error-handling/2-custom-errors/1-format-error/solution.md
  1-js/10-error-handling/2-custom-errors/1-format-error/task.md
  1-js/10-error-handling/2-custom-errors/article.md
Labels: needs +1

#281 Async iterators and generators
  1-js/12-generators-iterators/2-async-iterators-generators/article.md
Labels: needs +1

#255 Developer console
  1-js/01-getting-started/4-devtools/article.md
  1-js/01-getting-started/4-devtools/bug.html
Labels: needs +1

#191 Prototypal inheritance
  1-js/08-prototypes/01-prototype-inheritance/1-property-after-delete/solution.md
  1-js/08-prototypes/01-prototype-inheritance/1-property-after-delete/task.md
  1-js/08-prototypes/01-prototype-inheritance/2-search-algorithm/solution.md
  1-js/08-prototypes/01-prototype-inheritance/2-search-algorithm/task.md
  1-js/08-prototypes/01-prototype-inheritance/3-proto-and-this/solution.md
  1-js/08-prototypes/01-prototype-inheritance/3-proto-and-this/task.md
  1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/solution.md
  1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/task.md
  1-js/08-prototypes/01-prototype-inheritance/article.md
Labels: needs +1
