Repository javascript-tutorial/es.javascript.info, pull requests merged in 2020-07, with the labels that each got.

#273 Constructor, operator "new"
  1-js/04-object-basics/06-constructor-new/1-two-functions-one-object/solution.md
  1-js/04-object-basics/06-constructor-new/1-two-functions-one-object/task.md
  1-js/04-object-basics/06-constructor-new/2-calculator-constructor/_js.view/test.js
  1-js/04-object-basics/06-constructor-new/2-calculator-constructor/task.md
  1-js/04-object-basics/06-constructor-new/3-accumulator/_js.view/test.js
  1-js/04-object-basics/06-constructor-new/3-accumulator/solution.md
  1-js/04-object-basics/06-constructor-new/3-accumulator/task.md
  1-js/04-object-basics/06-constructor-new/article.md
Labels: review needed

#183 Property flags and descriptors
  1-js/07-object-properties/01-property-descriptors/article.md
Labels: needs +1

#192 F.prototype
  1-js/08-prototypes/02-function-prototype/1-changing-prototype/solution.md
  1-js/08-prototypes/02-function-prototype/1-changing-prototype/task.md
  1-js/08-prototypes/02-function-prototype/4-new-object-same-constructor/solution.md
  1-js/08-prototypes/02-function-prototype/4-new-object-same-constructor/task.md
  1-js/08-prototypes/02-function-prototype/article.md
Labels: needs +1

#190 Optional chaining '?.'
  1-js/04-object-basics/07-optional-chaining/article.md
Labels: needs +1

#205 Decorators and forwarding, call/apply
  1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/02-delay/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/02-delay/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/article.md
Labels: needs +1

#230 Functions
  1-js/02-first-steps/15-function-basics/1-if-else-required/solution.md
  1-js/02-first-steps/15-function-basics/1-if-else-required/task.md
  1-js/02-first-steps/15-function-basics/2-rewrite-function-question-or/solution.md
  1-js/02-first-steps/15-function-basics/2-rewrite-function-question-or/task.md
  1-js/02-first-steps/15-function-basics/3-min/solution.md
  1-js/02-first-steps/15-function-basics/3-min/task.md
  1-js/02-first-steps/15-function-basics/4-pow/solution.md
  1-js/02-first-steps/15-function-basics/4-pow/task.md
  1-js/02-first-steps/15-function-basics/article.md
Labels: needs +1

#193 Native prototypes
  1-js/08-prototypes/03-native-prototypes/1-defer-to-prototype/solution.md
  1-js/08-prototypes/03-native-prototypes/1-defer-to-prototype/task.md
  1-js/08-prototypes/03-native-prototypes/2-defer-to-prototype-extended/solution.md
  1-js/08-prototypes/03-native-prototypes/2-defer-to-prototype-extended/task.md
  1-js/08-prototypes/03-native-prototypes/article.md
Labels: changes requested

#252 Symbol type
  1-js/04-object-basics/08-symbol/article.md
Labels: needs +1

#263 Map and Set
  1-js/05-data-types/07-map-set/01-array-unique-map/task.md
  1-js/05-data-types/07-map-set/02-filter-anagrams/solution.md
  1-js/05-data-types/07-map-set/02-filter-anagrams/task.md
  1-js/05-data-types/07-map-set/03-iterable-keys/solution.md
  1-js/05-data-types/07-map-set/03-iterable-keys/task.md
  1-js/05-data-types/07-map-set/article.md
Labels: needs +1

#272 Function expressions
  1-js/02-first-steps/16-function-expressions/article.md
Labels: needs +1

#277 Traducción task Localstorage
  6-data-storage/02-localstorage/1-form-autosave/task.md
Labels: needs +1

#265 Character classes
  9-regular-expressions/02-regexp-character-classes/article.md
Labels: needs +1

#266 Unicode: flag "u" and class \p{...}
  9-regular-expressions/03-regexp-unicode/article.md
Labels: needs +1

#268 Anchors: string start ^ and end $
  9-regular-expressions/04-regexp-anchors/1-start-end/solution.md
  9-regular-expressions/04-regexp-anchors/1-start-end/task.md
  9-regular-expressions/04-regexp-anchors/article.md
Labels: needs +1

#269 Multiline mode of anchors ^ $, flag "m"
  9-regular-expressions/05-regexp-multiline-mode/article.md
Labels: needs +1

#290 Mouse events
  2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/solution.view/index.html
  2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/source.view/index.html
  2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/task.md
  2-ui/3-event-details/1-mouse-events-basics/article.md
Labels: needs +1

#259 Destructuring assignment
  1-js/05-data-types/10-destructuring-assignment/1-destruct-user/task.md
  1-js/05-data-types/10-destructuring-assignment/6-max-salary/_js.view/test.js
  1-js/05-data-types/10-destructuring-assignment/6-max-salary/task.md
  1-js/05-data-types/10-destructuring-assignment/article.md
Labels: needs +1

#293 Sincronización 5 Julio
  1-js/02-first-steps/09-comparison/article.md
  1-js/05-data-types/02-number/article.md
  1-js/05-data-types/09-keys-values-entries/article.md
  1-js/06-advanced-functions/03-closure/article.md
  1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/_js.view/solution.js
  1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/_js.view/source.js
  1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/_js.view/test.js
  1-js/09-classes/01-class/article.md
  1-js/09-classes/02-class-inheritance/article.md
  1-js/11-async/05-promise-api/article.md
  1-js/13-modules/01-modules-intro/article.md
  2-ui/1-document/01-browser-environment/article.md
  2-ui/1-document/07-modifying-document/article.md
  2-ui/1-document/11-coordinates/article.md
  2-ui/3-event-details/6-pointer-events/article.md
  6-data-storage/03-indexeddb/article.md
  9-regular-expressions/03-regexp-unicode/article.md
  9-regular-expressions/06-regexp-boundary/article.md
Labels: needs +1

#280 Microtasks
  1-js/11-async/07-microtask-queue/article.md
Labels: needs +1

#288 Promise
  1-js/11-async/02-promise-basics/01-re-resolve/solution.md
  1-js/11-async/02-promise-basics/01-re-resolve/task.md
  1-js/11-async/02-promise-basics/02-delay-promise/task.md
  1-js/11-async/02-promise-basics/03-animate-circle-promise/solution.view/index.html
  1-js/11-async/02-promise-basics/03-animate-circle-promise/task.md
  1-js/11-async/02-promise-basics/article.md
  1-js/11-async/02-promise-basics/head.html
Labels: ready to merge

#292 Native prototypes
  1-js/08-prototypes/03-native-prototypes/2-defer-to-prototype-extended/solution.md
  1-js/08-prototypes/03-native-prototypes/article.md
Labels: ready to merge

#295 Dynamic imports
  1-js/13-modules/03-modules-dynamic-imports/article.md
  1-js/13-modules/03-modules-dynamic-imports/say.view/index.html
  1-js/13-modules/03-modules-dynamic-imports/say.view/say.js
Labels: needs +1

#271 Mixins
  1-js/09-classes/07-mixins/article.md
  1-js/09-classes/07-mixins/head.html
Labels: ready to merge

#282 Word boundary: \b
  9-regular-expressions/06-regexp-boundary/1-find-time-hh-mm/solution.md
  9-regular-expressions/06-regexp-boundary/1-find-time-hh-mm/task.md
  9-regular-expressions/06-regexp-boundary/article.md
Labels: ready to merge

#284 Escaping, special characters
  9-regular-expressions/07-regexp-escaping/article.md
Labels: ready to merge

#275 Object.keys, values, entries
  1-js/05-data-types/09-keys-values-entries/01-sum-salaries/_js.view/test.js
  1-js/05-data-types/09-keys-values-entries/01-sum-salaries/solution.md
  1-js/05-data-types/09-keys-values-entries/01-sum-salaries/task.md
  1-js/05-data-types/09-keys-values-entries/02-count-properties/_js.view/test.js
  1-js/05-data-types/09-keys-values-entries/02-count-properties/task.md
  1-js/05-data-types/09-keys-values-entries/article.md
Labels: ready to merge

#279 Error handling, "try..catch"
  1-js/10-error-handling/1-try-catch/1-finally-or-code-after/solution.md
  1-js/10-error-handling/1-try-catch/1-finally-or-code-after/task.md
  1-js/10-error-handling/1-try-catch/article.md
  1-js/10-error-handling/index.md
Labels: ready to merge

#296 Sets and ranges [...]
  9-regular-expressions/08-regexp-character-sets-and-ranges/1-find-range-1/solution.md
  9-regular-expressions/08-regexp-character-sets-and-ranges/1-find-range-1/task.md
  9-regular-expressions/08-regexp-character-sets-and-ranges/2-find-time-2-formats/solution.md
  9-regular-expressions/08-regexp-character-sets-and-ranges/2-find-time-2-formats/task.md
  9-regular-expressions/08-regexp-character-sets-and-ranges/article.md
Labels: ready to merge

#297 Quantifiers +, *, ? and {n}
  9-regular-expressions/09-regexp-quantifiers/1-find-text-manydots/solution.md
  9-regular-expressions/09-regexp-quantifiers/1-find-text-manydots/task.md
  9-regular-expressions/09-regexp-quantifiers/2-find-html-colors-6hex/solution.md
  9-regular-expressions/09-regexp-quantifiers/2-find-html-colors-6hex/task.md
  9-regular-expressions/09-regexp-quantifiers/article.md
Labels: ready to merge

#278 JSON methods, toJSON
  1-js/05-data-types/12-json/1-serialize-object/task.md
  1-js/05-data-types/12-json/2-serialize-event-circular/solution.md
  1-js/05-data-types/12-json/2-serialize-event-circular/task.md
  1-js/05-data-types/12-json/article.md
Labels: needs +1

#302 Moving the mouse: mouseover/out, mouseenter/leave
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/solution.view/index.html
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/source.view/index.html
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/task.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/solution.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/solution.view/hoverIntent.js
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/source.view/hoverIntent.js
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/task.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/mouseenter-mouseleave-delegation-2.view/script.js
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/mouseoverout.view/index.html
  2-ui/3-event-details/index.md
Labels: ready to merge

#300 The "switch" statement
  1-js/02-first-steps/14-switch/2-rewrite-if-switch/solution.md
  1-js/02-first-steps/14-switch/article.md
Labels: ready to merge

#303 Eval: run a code string
  1-js/99-js-misc/02-eval/1-eval-calculator/solution.md
  1-js/99-js-misc/02-eval/1-eval-calculator/task.md
  1-js/99-js-misc/02-eval/article.md
Labels: ready to merge

#305 BigInt
  1-js/99-js-misc/05-bigint/article.md
Labels: ready to merge

#287 Currying
  1-js/99-js-misc/03-currying-partials/article.md
Labels: needs +1, ready to merge

#306 Index
  1-js/01-getting-started/index.md
  1-js/02-first-steps/index.md
  1-js/03-code-quality/index.md
  1-js/04-object-basics/index.md
  1-js/05-data-types/index.md
  1-js/06-advanced-functions/index.md
  1-js/07-object-properties/index.md
  1-js/08-prototypes/index.md
  1-js/09-classes/index.md
  1-js/11-async/index.md
  1-js/12-generators-iterators/index.md
  1-js/13-modules/index.md
  1-js/99-js-misc/index.md
  1-js/index.md
  2-ui/99-ui-misc/index.md
  2-ui/index.md
  3-frames-and-windows/index.md
  4-binary/index.md
  5-network/index.md
  6-data-storage/index.md
  7-animation/index.md
  8-web-components/index.md
Labels: ready to merge

#304 Reference Type
  1-js/99-js-misc/04-reference-type/2-check-syntax/solution.md
  1-js/99-js-misc/04-reference-type/2-check-syntax/task.md
  1-js/99-js-misc/04-reference-type/3-why-this/solution.md
  1-js/99-js-misc/04-reference-type/3-why-this/task.md
  1-js/99-js-misc/04-reference-type/article.md
  1-js/99-js-misc/index.md
Labels: ready to merge

#311 Searching: getElement*, querySelector*
  2-ui/1-document/04-searching-elements-dom/1-find-elements/solution.md
  2-ui/1-document/04-searching-elements-dom/1-find-elements/table.html
  2-ui/1-document/04-searching-elements-dom/1-find-elements/task.md
  2-ui/1-document/04-searching-elements-dom/article.md
Labels: ready to merge

#309 Arrays
  1-js/05-data-types/04-array/1-item-value/solution.md
  1-js/05-data-types/04-array/1-item-value/task.md
  1-js/05-data-types/04-array/10-maximal-subarray/solution.md
  1-js/05-data-types/04-array/10-maximal-subarray/task.md
  1-js/05-data-types/04-array/2-create-array/task.md
  1-js/05-data-types/04-array/3-call-array-this/solution.md
  1-js/05-data-types/04-array/3-call-array-this/task.md
  1-js/05-data-types/04-array/5-array-input-sum/solution.md
  1-js/05-data-types/04-array/5-array-input-sum/task.md
  1-js/05-data-types/04-array/article.md
Labels: ready to merge

#314 Basic operators, maths
  1-js/02-first-steps/08-operators/1-increment-order/solution.md
  1-js/02-first-steps/08-operators/1-increment-order/task.md
  1-js/02-first-steps/08-operators/2-assignment-result/solution.md
  1-js/02-first-steps/08-operators/2-assignment-result/task.md
  1-js/02-first-steps/08-operators/3-primitive-conversions-questions/solution.md
  1-js/02-first-steps/08-operators/3-primitive-conversions-questions/task.md
  1-js/02-first-steps/08-operators/4-fix-prompt/solution.md
  1-js/02-first-steps/08-operators/4-fix-prompt/task.md
  1-js/02-first-steps/08-operators/article.md
Labels: needs +1

#316 Array methods
  1-js/05-data-types/05-array-methods/1-camelcase/_js.view/solution.js
  1-js/05-data-types/05-array-methods/1-camelcase/task.md
  1-js/05-data-types/05-array-methods/10-average-age/task.md
  1-js/05-data-types/05-array-methods/11-array-unique/solution.md
  1-js/05-data-types/05-array-methods/11-array-unique/task.md
  1-js/05-data-types/05-array-methods/12-reduce-object/task.md
  1-js/05-data-types/05-array-methods/2-filter-range/_js.view/solution.js
  1-js/05-data-types/05-array-methods/2-filter-range/solution.md
  1-js/05-data-types/05-array-methods/2-filter-range/task.md
  1-js/05-data-types/05-array-methods/3-filter-range-in-place/_js.view/solution.js
  1-js/05-data-types/05-array-methods/3-filter-range-in-place/solution.md
  1-js/05-data-types/05-array-methods/3-filter-range-in-place/task.md
  1-js/05-data-types/05-array-methods/4-sort-back/task.md
  1-js/05-data-types/05-array-methods/5-copy-sort-array/solution.md
  1-js/05-data-types/05-array-methods/5-copy-sort-array/task.md
  1-js/05-data-types/05-array-methods/6-array-get-names/task.md
  1-js/05-data-types/05-array-methods/6-calculator-extendable/solution.md
  1-js/05-data-types/05-array-methods/6-calculator-extendable/task.md
  1-js/05-data-types/05-array-methods/7-map-objects/solution.md
  1-js/05-data-types/05-array-methods/7-map-objects/task.md
  1-js/05-data-types/05-array-methods/8-sort-objects/solution.md
  1-js/05-data-types/05-array-methods/8-sort-objects/task.md
  1-js/05-data-types/05-array-methods/9-shuffle/solution.md
  1-js/05-data-types/05-array-methods/9-shuffle/task.md
  1-js/05-data-types/05-array-methods/article.md
Labels: ready to merge

#308 Object copying, references
  1-js/04-object-basics/02-object-copy/article.md
Labels: ready to merge

#312 The old "var"
  1-js/06-advanced-functions/04-var/article.md
Labels: needs +1

#321 Objects
  1-js/04-object-basics/01-object/2-hello-object/task.md
  1-js/04-object-basics/01-object/3-is-empty/_js.view/solution.js
  1-js/04-object-basics/01-object/3-is-empty/_js.view/test.js
  1-js/04-object-basics/01-object/3-is-empty/solution.md
  1-js/04-object-basics/01-object/3-is-empty/task.md
  1-js/04-object-basics/01-object/5-sum-object/task.md
  1-js/04-object-basics/01-object/8-multiply-numeric/_js.view/source.js
  1-js/04-object-basics/01-object/8-multiply-numeric/_js.view/test.js
  1-js/04-object-basics/01-object/8-multiply-numeric/task.md
  1-js/04-object-basics/01-object/article.md
Labels: ready to merge

#318 Walking the DOM
  2-ui/1-document/03-dom-navigation/1-dom-children/solution.md
  2-ui/1-document/03-dom-navigation/1-dom-children/task.md
  2-ui/1-document/03-dom-navigation/3-navigation-links-which-null/task.md
  2-ui/1-document/03-dom-navigation/4-select-diagonal-cells/solution.md
  2-ui/1-document/03-dom-navigation/4-select-diagonal-cells/task.md
  2-ui/1-document/03-dom-navigation/article.md
Labels: ready to merge

#322 Index Update
  2-ui/1-document/index.md
  2-ui/2-events/index.md
  2-ui/4-forms-controls/index.md
  2-ui/5-loading/index.md
Labels: ready to merge

#324 Scripts: async, defer
  2-ui/5-loading/02-script-async-defer/article.md
Labels: ready to merge

#326 sync25Jul
  1-js/02-first-steps/05-types/article.md
  1-js/02-first-steps/06-alert-prompt-confirm/article.md
  1-js/02-first-steps/09-comparison/article.md
  1-js/02-first-steps/12-nullish-coalescing-operator/article.md
  1-js/04-object-basics/07-optional-chaining/article.md
  1-js/04-object-basics/08-symbol/article.md
  1-js/06-advanced-functions/10-bind/article.md
  1-js/08-prototypes/04-prototype-methods/article.md
  1-js/10-error-handling/1-try-catch/article.md
  1-js/11-async/04-promise-error-handling/article.md
  2-ui/1-document/07-modifying-document/article.md
  2-ui/2-events/01-introduction-browser-events/article.md
  2-ui/2-events/02-bubbling-and-capturing/article.md
  2-ui/3-event-details/4-mouse-drag-and-drop/ball.view/index.html
  3-frames-and-windows/03-cross-window-communication/sandbox.view/index.html
  5-network/07-url/article.md
  6-data-storage/02-localstorage/article.md
Labels: needs +1

#323 Attributes and properties
  2-ui/1-document/06-dom-attributes-and-properties/1-get-user-attribute/solution.md
  2-ui/1-document/06-dom-attributes-and-properties/1-get-user-attribute/task.md
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/solution.md
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/solution.view/index.html
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/source.view/index.html
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/task.md
  2-ui/1-document/06-dom-attributes-and-properties/article.md
Labels: ready to merge

#328 Window sizes and scrolling
  2-ui/1-document/10-size-and-scroll-window/article.md
Labels: needs +1

#329 Error handling with promises
  1-js/11-async/04-promise-error-handling/01-error-async/solution.md
  1-js/11-async/04-promise-error-handling/01-error-async/task.md
  1-js/11-async/04-promise-error-handling/article.md
  1-js/11-async/04-promise-error-handling/getMessage.js
Labels: ready to merge

#317 Async/await
  1-js/11-async/08-async-await/01-rewrite-async/solution.md
  1-js/11-async/08-async-await/01-rewrite-async/task.md
  1-js/11-async/08-async-await/02-rewrite-async-2/solution.md
  1-js/11-async/08-async-await/02-rewrite-async-2/task.md
  1-js/11-async/08-async-await/03-async-from-regular/solution.md
  1-js/11-async/08-async-await/03-async-from-regular/task.md
  1-js/11-async/08-async-await/article.md
Labels: ready to merge
