Repository javascript-tutorial/es.javascript.info, pull requests merged in 2020-10, with the labels that each got.

#389 JavaScript animations
  7-animation/3-js-animation/1-animate-ball/solution.md
  7-animation/3-js-animation/1-animate-ball/task.md
  7-animation/3-js-animation/2-animate-ball-hops/solution.md
  7-animation/3-js-animation/2-animate-ball-hops/task.md
  7-animation/3-js-animation/article.md
  7-animation/3-js-animation/move-raf.view/index.html
  7-animation/3-js-animation/text.view/index.html
Labels: ready to merge

#392 Introduction to browser events
  2-ui/2-events/01-introduction-browser-events/01-hide-other/solution.view/index.html
  2-ui/2-events/01-introduction-browser-events/01-hide-other/source.view/index.html
  2-ui/2-events/01-introduction-browser-events/01-hide-other/task.md
  2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/solution.md
  2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/task.md
  2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/solution.md
  2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/task.md
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.view/index.html
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/source.view/index.html
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/task.md
  2-ui/2-events/01-introduction-browser-events/05-sliding-menu/solution.md
  2-ui/2-events/01-introduction-browser-events/05-sliding-menu/task.md
  2-ui/2-events/01-introduction-browser-events/06-hide-message/solution.md
  2-ui/2-events/01-introduction-browser-events/06-hide-message/solution.view/index.html
  2-ui/2-events/01-introduction-browser-events/06-hide-message/task.md
  2-ui/2-events/01-introduction-browser-events/07-carousel/solution.md
  2-ui/2-events/01-introduction-browser-events/07-carousel/solution.view/index.html
  2-ui/2-events/01-introduction-browser-events/07-carousel/solution.view/style.css
  2-ui/2-events/01-introduction-browser-events/07-carousel/source.view/index.html
  2-ui/2-events/01-introduction-browser-events/07-carousel/source.view/style.css
  2-ui/2-events/01-introduction-browser-events/07-carousel/task.md
  2-ui/2-events/01-introduction-browser-events/article.md
Labels: ready to merge

#401 Update article.md
  2-ui/5-loading/03-onload-onerror/article.md
Labels: review needed

#397 Fetch API
  5-network/06-fetch-api/article.md
  5-network/06-fetch-api/post.view/server.js
Labels: ready to merge

#400 Transltion of sum to task and solution
  1-js/06-advanced-functions/01-recursion/01-sum-to/solution.md
  1-js/06-advanced-functions/01-recursion/01-sum-to/task.md
Labels: ready to merge

#386 Shadow DOM
  8-web-components/3-shadow-dom/article.md
Labels: changes requested

#409 Add translation for all the tasks in 1.6.1
  1-js/06-advanced-functions/01-recursion/02-factorial/solution.md
  1-js/06-advanced-functions/01-recursion/02-factorial/task.md
  1-js/06-advanced-functions/01-recursion/03-fibonacci-numbers/solution.md
  1-js/06-advanced-functions/01-recursion/03-fibonacci-numbers/task.md
  1-js/06-advanced-functions/01-recursion/04-output-single-linked-list/solution.md
  1-js/06-advanced-functions/01-recursion/04-output-single-linked-list/task.md
  1-js/06-advanced-functions/01-recursion/05-output-single-linked-list-reverse/solution.md
  1-js/06-advanced-functions/01-recursion/05-output-single-linked-list-reverse/task.md
Labels: needs +1

#410 Translate arrays comparasion
  1-js/05-data-types/04-array/article.md
Labels: needs +1

#412 Translate 1.9.3.3 task and solution
  1-js/09-classes/03-static-properties-methods/3-class-extend-object/solution.md
  1-js/09-classes/03-static-properties-methods/3-class-extend-object/task.md
Labels: ready to merge

#416 Update closure solution.md
  1-js/06-advanced-functions/03-closure/10-make-army/solution.md
Labels: needs +1

#421 fix-svg-from-eng
  1-js/03-code-quality/01-debugging-chrome/chrome-sources-breakpoint.svg
Labels: review needed

#414 Methods of RegExp and String
  9-regular-expressions/17-regexp-methods/article.md
Labels: ready to merge

#422 Node properties: type, tag and contents
  2-ui/1-document/05-basic-dom-node-properties/2-lastchild-nodetype-inline/solution.md
  2-ui/1-document/05-basic-dom-node-properties/2-lastchild-nodetype-inline/task.md
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/solution.md
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/solution.view/index.html
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/source.view/index.html
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/task.md
  2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/solution.md
  2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/task.md
  2-ui/1-document/05-basic-dom-node-properties/4-where-document-in-hierarchy/solution.md
  2-ui/1-document/05-basic-dom-node-properties/4-where-document-in-hierarchy/task.md
  2-ui/1-document/05-basic-dom-node-properties/article.md
Labels: ready to merge

#425 Fetch: Download progress
  5-network/03-fetch-progress/article.md
  5-network/03-fetch-progress/progress.view/index.html
Labels: ready to merge

#384 Template element
  8-web-components/4-template-element/article.md
Labels: ready to merge

#413 Styles and classes
  2-ui/1-document/08-styles-and-classes/2-create-notification/task.md
  2-ui/1-document/08-styles-and-classes/article.md
Labels: ready to merge

#415 Susy201010
  1-js/01-getting-started/1-intro/article.md
  1-js/02-first-steps/18-javascript-specials/article.md
  1-js/04-object-basics/02-object-copy/article.md
  2-ui/5-loading/02-script-async-defer/article.md
  3-frames-and-windows/01-popup-windows/article.md
  6-data-storage/03-indexeddb/article.md
  README.md
Labels: needs +1, review needed

#429 5.3 fetch progress. It is not Its, it is it's instead. =) La frase tiene sentido como "Es un"
  5-network/03-fetch-progress/article.md
Labels: ready to merge

#419 1.4.7 opt chaining update from ENG
  1-js/04-object-basics/07-optional-chaining/article.md
Labels: ready to merge

#417 1 9 2 class inherit extendido y correcciones
  1-js/09-classes/02-class-inheritance/1-class-constructor-error/task.md
  1-js/09-classes/02-class-inheritance/article.md
Labels: ready to merge

#420 1-6-3 closure 10 army solution - fix last eng update
  1-js/06-advanced-functions/03-closure/10-make-army/solution.md
Labels: ready to merge

#432 fix format 1-6-3-10 sol
  1-js/06-advanced-functions/03-closure/10-make-army/solution.md
Labels: review needed

#426 Shadow DOM styling
  8-web-components/6-shadow-dom-style/article.md
Labels: needs +1

#430 8 4 template, arreglos post puesta online
  8-web-components/4-template-element/article.md
Labels: ready to merge

#434 Update article.md
  8-web-components/3-shadow-dom/article.md
Labels: needs +1

#427 Fetch: Cross-Origin Requests
  5-network/05-fetch-crossorigin/1-do-we-need-origin/solution.md
  5-network/05-fetch-crossorigin/1-do-we-need-origin/task.md
  5-network/05-fetch-crossorigin/article.md
Labels: ready to merge

#435 Fetch
  5-network/01-fetch/01-fetch-users/_js.view/source.js
  5-network/01-fetch/01-fetch-users/solution.md
  5-network/01-fetch/01-fetch-users/task.md
  5-network/01-fetch/article.md
Labels: ready to merge
