Repository javascript-tutorial/es.javascript.info, pull requests merged in 2020-08, with the labels that each got.

#330 Scrolling
  2-ui/3-event-details/8-onscroll/1-endless-page/solution.md
  2-ui/3-event-details/8-onscroll/1-endless-page/task.md
  2-ui/3-event-details/8-onscroll/2-updown-button/task.md
  2-ui/3-event-details/8-onscroll/3-load-visible-img/solution.md
  2-ui/3-event-details/8-onscroll/3-load-visible-img/task.md
  2-ui/3-event-details/8-onscroll/article.md
Labels: ready to merge

#325 File and FileReader
  4-binary/04-file/article.md
Labels: needs +1

#334 Arrow functions, the basics
  1-js/02-first-steps/17-arrow-functions-basics/1-rewrite-arrow/solution.md
  1-js/02-first-steps/17-arrow-functions-basics/1-rewrite-arrow/task.md
  1-js/02-first-steps/17-arrow-functions-basics/article.md
Labels: ready to merge

#331 From the orbital height
  8-web-components/1-webcomponents-intro/article.md
Labels: needs +1

#333 Events: change, input, cut, copy, paste
  2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/solution.view/index.html
  2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/source.view/index.html
  2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/task.md
  2-ui/4-forms-controls/3-events-change-input/article.md
Labels: needs +1, review needed

#313 Promise API
  1-js/11-async/05-promise-api/article.md
Labels: needs +1

#335 FormData
  5-network/02-formdata/article.md
  5-network/02-formdata/post.view/server.js
Labels: needs +1

#336 Pointer events
  2-ui/3-event-details/6-pointer-events/article.md
Labels: needs +1

#338 TextDecoder and TextEncoder
  4-binary/02-text-decoder/article.md
Labels: ready to merge

#339 Update section AN INTRODUCTION
  1-js/01-getting-started/1-intro/article.md
  1-js/01-getting-started/3-code-editors/article.md
  1-js/01-getting-started/4-devtools/article.md
Labels: needs +1

#345 Capturing groups
  9-regular-expressions/11-regexp-groups/01-test-mac/solution.md
  9-regular-expressions/11-regexp-groups/01-test-mac/task.md
  9-regular-expressions/11-regexp-groups/02-find-webcolor-3-or-6/solution.md
  9-regular-expressions/11-regexp-groups/02-find-webcolor-3-or-6/task.md
  9-regular-expressions/11-regexp-groups/03-find-decimal-numbers/solution.md
  9-regular-expressions/11-regexp-groups/03-find-decimal-numbers/task.md
  9-regular-expressions/11-regexp-groups/04-parse-expression/solution.md
  9-regular-expressions/11-regexp-groups/04-parse-expression/task.md
  9-regular-expressions/11-regexp-groups/article.md
Labels: changes requested

#341 Class basic syntax
  1-js/09-classes/01-class/1-rewrite-to-class/task.md
  1-js/09-classes/01-class/article.md
Labels: needs +1

#343 Object methods, "this"
  1-js/04-object-basics/04-object-methods/4-object-property-this/solution.md
  1-js/04-object-basics/04-object-methods/4-object-property-this/task.md
  1-js/04-object-basics/04-object-methods/7-calculator/task.md
  1-js/04-object-basics/04-object-methods/8-chain-calls/task.md
  1-js/04-object-basics/04-object-methods/article.md
Labels: needs +1

#350 Object to primitive conversion
  1-js/04-object-basics/09-object-toprimitive/article.md
Labels: needs +1

#342 rev 1-2-1 a 1-2-5
  1-js/02-first-steps/01-hello-world/article.md
  1-js/02-first-steps/02-structure/article.md
  1-js/02-first-steps/03-strict-mode/article.md
  1-js/02-first-steps/04-variables/2-declare-variables/solution.md
  1-js/02-first-steps/04-variables/article.md
  1-js/02-first-steps/04-variables/variable-change.svg
  1-js/02-first-steps/04-variables/variable.svg
  1-js/02-first-steps/05-types/article.md
Labels: needs +1

#360 Fetch: Abort
  5-network/04-fetch-abort/article.md
Labels: ready to merge

#356 Backreferences in pattern: \N and \k
  9-regular-expressions/12-regexp-backreferences/article.md
Labels: ready to merge

#354 Long polling
  5-network/10-long-polling/article.md
  5-network/10-long-polling/longpoll.view/browser.js
  5-network/10-long-polling/longpoll.view/index.html
  5-network/10-long-polling/longpoll.view/server.js
Labels: ready to merge

#352 Date and Time
  1-js/05-data-types/11-date/1-new-date/solution.md
  1-js/05-data-types/11-date/1-new-date/task.md
  1-js/05-data-types/11-date/2-get-week-day/solution.md
  1-js/05-data-types/11-date/2-get-week-day/task.md
  1-js/05-data-types/11-date/3-weekday/task.md
  1-js/05-data-types/11-date/4-get-date-ago/solution.md
  1-js/05-data-types/11-date/4-get-date-ago/task.md
  1-js/05-data-types/11-date/5-last-day-of-month/solution.md
  1-js/05-data-types/11-date/5-last-day-of-month/task.md
  1-js/05-data-types/11-date/6-get-seconds-today/solution.md
  1-js/05-data-types/11-date/6-get-seconds-today/task.md
  1-js/05-data-types/11-date/7-get-seconds-to-tomorrow/solution.md
  1-js/05-data-types/11-date/7-get-seconds-to-tomorrow/task.md
  1-js/05-data-types/11-date/8-format-date-relative/solution.md
  1-js/05-data-types/11-date/8-format-date-relative/task.md
  1-js/05-data-types/11-date/article.md
Labels: ready to merge

#358 Event loop: microtasks and macrotasks
  2-ui/99-ui-misc/03-event-loop/article.md
Labels: needs +1, review needed

#355 Greedy and lazy quantifiers
  9-regular-expressions/10-regexp-greedy-and-lazy/1-lazy-greedy/solution.md
  9-regular-expressions/10-regexp-greedy-and-lazy/1-lazy-greedy/task.md
  9-regular-expressions/10-regexp-greedy-and-lazy/3-find-html-comments/solution.md
  9-regular-expressions/10-regexp-greedy-and-lazy/3-find-html-comments/task.md
  9-regular-expressions/10-regexp-greedy-and-lazy/4-find-html-tags-greedy-lazy/solution.md
  9-regular-expressions/10-regexp-greedy-and-lazy/4-find-html-tags-greedy-lazy/task.md
  9-regular-expressions/10-regexp-greedy-and-lazy/article.md
Labels: changes requested, needs +1

#361 sync27Agosto
  1-js/01-getting-started/1-intro/article.md
  1-js/02-first-steps/11-logical-operators/article.md
  1-js/05-data-types/04-array/article.md
  1-js/05-data-types/05-array-methods/6-calculator-extendable/_js.view/solution.js
  1-js/06-advanced-functions/03-closure/article.md
  1-js/06-advanced-functions/05-global-object/article.md
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/task.md
  1-js/08-prototypes/01-prototype-inheritance/article.md
  1-js/09-classes/07-mixins/article.md
  1-js/11-async/08-async-await/article.md
  1-js/99-js-misc/04-reference-type/article.md
  2-ui/1-document/11-coordinates/article.md
  2-ui/2-events/02-bubbling-and-capturing/article.md
  2-ui/3-event-details/4-mouse-drag-and-drop/article.md
  2-ui/3-event-details/6-pointer-events/article.md
  2-ui/3-event-details/8-onscroll/1-endless-page/solution.md
  2-ui/3-event-details/8-onscroll/article.md
  2-ui/4-forms-controls/2-focus-blur/article.md
  3-frames-and-windows/01-popup-windows/article.md
  5-network/01-fetch/01-fetch-users/solution.md
  5-network/06-fetch-api/article.md
  5-network/11-websocket/article.md
  6-data-storage/01-cookie/article.md
  9-regular-expressions/03-regexp-unicode/article.md
Labels: needs +1

#349 Coordinates
  2-ui/1-document/11-coordinates/1-find-point-coordinates/solution.md
  2-ui/1-document/11-coordinates/1-find-point-coordinates/solution.view/index.html
  2-ui/1-document/11-coordinates/1-find-point-coordinates/source.view/index.html
  2-ui/1-document/11-coordinates/1-find-point-coordinates/task.md
  2-ui/1-document/11-coordinates/2-position-at/solution.md
  2-ui/1-document/11-coordinates/2-position-at/solution.view/index.html
  2-ui/1-document/11-coordinates/2-position-at/source.view/index.html
  2-ui/1-document/11-coordinates/2-position-at/task.md
  2-ui/1-document/11-coordinates/3-position-at-absolute/solution.md
  2-ui/1-document/11-coordinates/3-position-at-absolute/solution.view/index.html
  2-ui/1-document/11-coordinates/3-position-at-absolute/task.md
  2-ui/1-document/11-coordinates/4-position-inside-absolute/solution.view/index.html
  2-ui/1-document/11-coordinates/4-position-inside-absolute/task.md
  2-ui/1-document/11-coordinates/article.md
  2-ui/1-document/11-coordinates/head.html
Labels: needs +1, review needed

#363 Dispatching custom events
  2-ui/2-events/05-dispatch-events/article.md
Labels: needs +1, review needed
