Repository javascript-tutorial/es.javascript.info, pull requests merged in 2020-09, with the labels that each got.

#367 Cross-window communication
  3-frames-and-windows/03-cross-window-communication/article.md
  3-frames-and-windows/03-cross-window-communication/postmessage.view/iframe.html
  3-frames-and-windows/03-cross-window-communication/postmessage.view/index.html
  3-frames-and-windows/03-cross-window-communication/sandbox.view/index.html
  3-frames-and-windows/03-cross-window-communication/sandbox.view/sandboxed.html
Labels: needs +1, review needed

#372 Bubbling and capturing
  2-ui/2-events/02-bubbling-and-capturing/article.md
  2-ui/2-events/02-bubbling-and-capturing/bubble-target.view/index.html
Labels: ready to merge

#374 The clickjacking attack
  3-frames-and-windows/06-clickjacking/article.md
  3-frames-and-windows/06-clickjacking/clickjacking-visible.view/facebook.html
  3-frames-and-windows/06-clickjacking/clickjacking-visible.view/index.html
  3-frames-and-windows/06-clickjacking/clickjacking.view/facebook.html
  3-frames-and-windows/06-clickjacking/clickjacking.view/index.html
  3-frames-and-windows/06-clickjacking/protector.view/iframe.html
  3-frames-and-windows/06-clickjacking/top-location.view/iframe.html
  3-frames-and-windows/06-clickjacking/top-location.view/index.html
Labels: ready to merge

#359 Popups and window methods
  3-frames-and-windows/01-popup-windows/article.md
Labels: ready to merge

#377 XMLHttpRequest
  5-network/08-xmlhttprequest/article.md
Labels: ready to merge

#378 Browser default actions
  2-ui/2-events/04-default-browser-action/1-why-return-false-fails/solution.md
  2-ui/2-events/04-default-browser-action/1-why-return-false-fails/task.md
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/solution.md
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/solution.view/index.html
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/source.view/index.html
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/task.md
  2-ui/2-events/04-default-browser-action/3-image-gallery/solution.md
  2-ui/2-events/04-default-browser-action/3-image-gallery/solution.view/index.html
  2-ui/2-events/04-default-browser-action/3-image-gallery/source.view/index.html
  2-ui/2-events/04-default-browser-action/3-image-gallery/task.md
  2-ui/2-events/04-default-browser-action/article.md
  2-ui/2-events/04-default-browser-action/menu.view/menu.js
Labels: ready to merge

#370 Generators
  1-js/12-generators-iterators/1-generators/01-pseudo-random-generator/solution.md
  1-js/12-generators-iterators/1-generators/01-pseudo-random-generator/task.md
  1-js/12-generators-iterators/1-generators/article.md
Labels: needs +1

#369 Page: DOMContentLoaded, load, beforeunload, unload
  2-ui/5-loading/01-onload-ondomcontentloaded/article.md
Labels: needs +1

#380 Blob
  4-binary/03-blob/article.md
Labels: ready to merge

#375 Resumable file upload
  5-network/09-resume-upload/article.md
Labels: review needed

#353 Event delegation
  2-ui/2-events/03-event-delegation/1-hide-message-delegate/task.md
  2-ui/2-events/03-event-delegation/2-sliding-tree/solution.md
  2-ui/2-events/03-event-delegation/2-sliding-tree/task.md
  2-ui/2-events/03-event-delegation/3-sortable-table/task.md
  2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md
  2-ui/2-events/03-event-delegation/article.md
Labels: needs +1

#376 URL objects
  5-network/07-url/article.md
Labels: ready to merge

#381 Server Sent Events
  5-network/12-server-sent-events/article.md
  5-network/12-server-sent-events/eventsource.view/index.html
Labels: needs +1, review needed

#382 Selection and Range
  2-ui/99-ui-misc/02-selection-range/article.md
Labels: needs +1
