Repository javascript-tutorial/es.javascript.info, pull requests merged in 2020-12, with the labels that each got.

#454 Forms: event and method submit
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/solution.md
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/solution.view/index.html
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/source.view/index.html
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/task.md
  2-ui/4-forms-controls/4-forms-submit/article.md
Labels: ready to merge

#456 traducir header olvidado
  2-ui/4-forms-controls/4-forms-submit/article.md
Labels: review needed

#449 Susy201124
  1-js/02-first-steps/01-hello-world/article.md
  1-js/04-object-basics/01-object/article.md
  1-js/04-object-basics/02-object-copy/article.md
  2-ui/4-forms-controls/3-events-change-input/article.md
  2-ui/5-loading/01-onload-ondomcontentloaded/article.md
  2-ui/5-loading/02-script-async-defer/article.md
Labels: needs +1

#424 Sticky flag "y", searching at position
  9-regular-expressions/16-regexp-sticky/article.md
Labels: needs +1

#431 Form properties and methods
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/solution.md
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/task.md
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.md
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/task.md
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/solution.md
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/task.md
  2-ui/4-forms-controls/1-form-elements/article.md
Labels: needs +1

#433 Element size and scrolling
  2-ui/1-document/09-size-and-scroll/1-get-scroll-height-bottom/solution.md
  2-ui/1-document/09-size-and-scroll/1-get-scroll-height-bottom/task.md
  2-ui/1-document/09-size-and-scroll/2-scrollbar-width/solution.md
  2-ui/1-document/09-size-and-scroll/2-scrollbar-width/task.md
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/solution.md
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/task.md
  2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/solution.md
  2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/task.md
  2-ui/1-document/09-size-and-scroll/article.md
  2-ui/1-document/09-size-and-scroll/cssWidthScroll.view/index.html
Labels: ready to merge

#391 Data types
  1-js/02-first-steps/05-types/1-string-quotes/solution.md
  1-js/02-first-steps/05-types/1-string-quotes/task.md
  1-js/02-first-steps/05-types/article.md
Labels: ready to merge
