Repository javascript-tutorial/es.javascript.info, pull requests merged in 2021-08, with the labels that each got.

#535 Primera pruena de propuestas de cambios en la redacción.
  1-js/02-first-steps/05-types/article.md
Labels: review needed

#491 IndexedDB
  6-data-storage/03-indexeddb/article.md
Labels: changes requested

#537 pointless
  2-ui/3-event-details/6-pointer-events/article.md
Labels: review needed

#539 fix spanish translation
  1-js/02-first-steps/08-operators/article.md
Labels: needs +1
