Repository javascript-tutorial/es.javascript.info, pull requests merged in 2021-03, with the labels that each got.

#489 Corregido error de redacción
  1-js/02-first-steps/10-ifelse/article.md
Labels: needs +1

#485 1-2-12 Nullish - cierra #402
  1-js/02-first-steps/12-nullish-coalescing-operator/article.md
Labels: changes requested

#496 Misspelling
  5-network/01-fetch/01-fetch-users/solution.md
Labels: needs +1

#497 Misspelling
  5-network/02-formdata/article.md
Labels: review needed

#498 Misspelling
  5-network/03-fetch-progress/article.md
Labels: review needed

#499 Misspelling
  5-network/05-fetch-crossorigin/article.md
Labels: review needed

#502 typos
  2-ui/1-document/02-dom-nodes/article.md
  2-ui/1-document/03-dom-navigation/3-navigation-links-which-null/solution.md
  2-ui/1-document/03-dom-navigation/article.md
  2-ui/1-document/04-searching-elements-dom/article.md
  2-ui/1-document/08-styles-and-classes/article.md
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/solution.md
  2-ui/1-document/09-size-and-scroll/article.md
  2-ui/1-document/11-coordinates/article.md
  2-ui/2-events/01-introduction-browser-events/article.md
  2-ui/2-events/02-bubbling-and-capturing/article.md
  2-ui/3-event-details/1-mouse-events-basics/article.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/task.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
  2-ui/3-event-details/4-mouse-drag-and-drop/article.md
  2-ui/3-event-details/6-pointer-events/article.md
  2-ui/3-event-details/8-onscroll/3-load-visible-img/task.md
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/task.md
  2-ui/4-forms-controls/1-form-elements/article.md
  2-ui/4-forms-controls/3-events-change-input/article.md
  2-ui/4-forms-controls/4-forms-submit/article.md
  2-ui/5-loading/01-onload-ondomcontentloaded/article.md
  2-ui/5-loading/03-onload-onerror/1-load-img-callback/task.md
  2-ui/5-loading/03-onload-onerror/article.md
  3-frames-and-windows/01-popup-windows/article.md
  4-binary/03-blob/article.md
  4-binary/04-file/article.md
  5-network/01-fetch/article.md
  5-network/04-fetch-abort/article.md
  5-network/08-xmlhttprequest/article.md
  5-network/09-resume-upload/article.md
  5-network/11-websocket/article.md
  6-data-storage/02-localstorage/article.md
  7-animation/3-js-animation/article.md
  8-web-components/1-webcomponents-intro/article.md
  9-regular-expressions/02-regexp-character-classes/article.md
  9-regular-expressions/08-regexp-character-sets-and-ranges/2-find-time-2-formats/task.md
  9-regular-expressions/10-regexp-greedy-and-lazy/article.md
  9-regular-expressions/11-regexp-groups/02-find-webcolor-3-or-6/solution.md
Labels: review needed

#505 err conceptual simple X safe - cierra #460
  5-network/05-fetch-crossorigin/article.md
Labels: review needed
