Repository javascript-tutorial/es.javascript.info, pull requests merged in 2022-05, with the labels that each got.

#619 Update article.md
  1-js/02-first-steps/15-function-basics/article.md
Labels: changes requested

#623 Susy220504
  1-js/02-first-steps/04-variables/article.md
  1-js/02-first-steps/14-switch/article.md
  1-js/02-first-steps/16-function-expressions/article.md
  1-js/03-code-quality/05-testing-mocha/article.md
  1-js/04-object-basics/02-object-copy/article.md
  1-js/04-object-basics/08-symbol/article.md
  1-js/05-data-types/01-primitives-methods/1-string-new-property/task.md
  1-js/05-data-types/02-number/article.md
  1-js/05-data-types/03-string/article.md
  1-js/06-advanced-functions/06-function-object/article.md
  1-js/06-advanced-functions/08-settimeout-setinterval/article.md
  1-js/09-classes/03-static-properties-methods/3-class-extend-object/solution.md
  1-js/09-classes/03-static-properties-methods/article.md
  2-ui/1-document/07-modifying-document/5-why-aaa/task.md
  2-ui/3-event-details/1-mouse-events-basics/article.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/solution.view/index.html
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/source.view/index.html
  3-frames-and-windows/06-clickjacking/article.md
  6-data-storage/01-cookie/article.md
  6-data-storage/02-localstorage/article.md
  7-animation/2-css-animations/article.md
  8-web-components/5-slots-composition/article.md
Labels: review needed

#624 Susy220512
  1-js/02-first-steps/18-javascript-specials/article.md
  1-js/03-code-quality/03-comments/article.md
  1-js/03-code-quality/06-polyfills/article.md
  1-js/04-object-basics/08-symbol/article.md
  1-js/04-object-basics/09-object-toprimitive/article.md
  1-js/05-data-types/04-array/article.md
  1-js/05-data-types/11-date/article.md
  1-js/08-prototypes/01-prototype-inheritance/article.md
  1-js/09-classes/02-class-inheritance/article.md
Labels: review needed

#626 Minor fix in example code
  1-js/05-data-types/10-destructuring-assignment/article.md
Labels: needs +1

#625 recursividad: partial != parcial y otros cambios
  1-js/06-advanced-functions/01-recursion/article.md
Labels: review needed

#627 Update article.md
  1-js/08-prototypes/03-native-prototypes/article.md
Labels: review needed
